"""add_celery_task_id_to_jobs

Revision ID: 90e62fc2e212
Revises: ea5eedbf92a8
Create Date: 2026-07-04 18:32:48.163537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90e62fc2e212'
down_revision: Union[str, Sequence[str], None] = 'ea5eedbf92a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('celery_task_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'celery_task_id')
    # ### end Alembic commands ###
